### ISSUE TITLE
Process fails at step 4

### ISSUE THREAD

**Issue by inardz** [InseeFrLab/k8s-onboarding#57]
Nothing happens when click on "COMMENCER A Y DEPLOYER DES APPLICATIONS"
![image](https://user-images.githubusercontent.com/32394730/101796540-4dbe6580-3b09-11eb-87e4-9a562e78faed.png)

**Comment by olevitt** [comment]
Thanks for the report :+1: 

I was able to reproduce this issue which is due to the fact that since #54 the bearer token is no longer sent with the request.  
We should probably :  
* Fix that so that the token is sent along the request  
* Prevent each step from completing if the status code is not 200 (in this case, each step results in a 401)

This should be relatively easy to fix
